require 'core.options'
require 'core.plugins'
require 'core.mappings'
require 'core.colorscheme'
require 'artur.comment'
-- require 'artur.nvim-tree'
require 'artur.bufferline'
require 'artur.statusline'
require 'artur.colorizer'
require 'artur.which-key'
require 'artur.treesitter'
require 'artur.autopairs'
require 'artur.hop'
require 'artur.telescope'
require 'artur.cmp'
require 'artur.lsp.mason'
require 'artur.lsp.lspsaga'
require 'artur.lsp.lspconfig'
require 'artur.lsp.null-ls'
require 'artur.symbols-outline'
require 'artur.twilight'

