require 'artur.options'
require 'artur.keymaps'
require 'artur.plugins'
require 'artur.toggleterm'
require 'artur.hop'
require 'artur.colorscheme'
-- require 'artur.cmp'
-- require 'artur.nvim_lsp_installer'
require 'artur.treesitter'
require 'artur.lsp':load()
require 'artur.nvim_tree'
require 'artur.telescope'
require 'artur.bufferline'
require 'artur.indent_line'
require 'artur.lualine'
require 'artur.autopairs'
require 'artur.symbols_outline'

